### PR TITLE
Fix compilation

### PR DESCRIPTION
**Pull request by fiam**
Backported from https://github.com/wxWidgets/wxWidgets/commit/d9deaa8b76128613a84f3d085eb1e4b05631083a

### CODE REVIEW

**Comment by fiam** [comment]
Some CI tests are failing because the environments are trying to install a non-existing package, but not because of changes in this PR. Should I fix those?

**Comment by alberto-frsky** [comment]
Could someone please take a look at this? Current package doesn't build on macOS nor on Linux.

**Comment by fiam** [comment]
Could someone please take a look at this? The package currently doesn't compile on macOS nor Linux, and the upstream fix is not even yet in a release.

**Review by Croydon — APPROVED** [review]

**Comment by Croydon** [comment]
> Some CI tests are failing because the environments are trying to install a non-existing package, but not because of changes in this PR. Should I fix those?

Since they don't happen because of this PR you don't need to. On the other hand, contributions are always very welcome :)

**Comment by alberto-frsky** [comment]
@Croydon Thank you so much for reviewing and merging it! Is it possible to use the recipe in the testing/3.1.3 branch from the https://api.bintray.com/conan/bincrafters/public-conan remote or do I need to setup my own one? Thanks!

**Comment by fiam** [comment]
@Croydon Thanks for reviewing and merging it! Is it possible to use the testing/3.1.3 branch from the public bincrafters remote or do I need to I need to set up my own one? Thanks!

P.S. Sorry for the double notification, accidentally commented with a company account.

**Comment by Croydon** [comment]
I have pushed the changes to `stable/` they should be available from the Conan remote

**Pull request merged**
