### PR TITLE
fix expat: use expatd on Windows Debug and drop unsupported platforms

### PR DESCRIPTION
**Pull request by cqjjjzr**
Provided a custom `FindEXPAT.cmake` to locate the expat properly on Windows, Debug build.

Dropped Clang 8 and GCC 9 since they're not supported by the CCI.

### CODE REVIEW

**Comment by cqjjjzr** [comment]
All Azure pipeline builds fail with weird problem. Could you please have a look at it?

**Comment by Croydon** [comment]
Pull request with AZP runs should be fixed now

**Comment by Croydon** [comment]
Custom CMake find scripts are pretty much something we want to get rid of.

Any idea what to do here @SSE4 or @uilianries? 

How to we make sure that Windows debug builds of wxwidgets can find expatd?

**Comment by cqjjjzr** [comment]
Could you please restart all the AZP builds?

**Comment by Croydon** [comment]
Restarted

**Comment by cqjjjzr** [comment]
It seems that this solution works pretty well. Any other workarounds? Can we patch the wxWidgets cmake files?

**Comment by SSE4** [comment]
@cqjjjzr do you think if we can use [cmake_find_package_multi](https://docs.conan.io/en/latest/reference/generators/cmake_find_package_multi.html) generator instead? so it generates `FindEXPAT.cmake` automatically, and we don't have to use a copy.

**Comment by cqjjjzr** [comment]
@SSE4 Can `cmake_find_package_multi` generator really generate `FindEXPAT.cmake`? My settings can only generator `expatTargets.cmake`, `expatConfig.cmake` and `expatTarget-release.cmake`. Also, I remember that `find_package` command is case-sensitive...

**Comment by SSE4** [comment]
@cqjjjzr 
1. no, it generates config files. they are still discovered by `find_package`. in general, `FindEXPAT.cmake` is old approach, and `EXPATTargets.cmake` is new approach (so-called modern CMake)
2. conan allows to hande name of the generated file. expat recipe should has the following in it:
```
self.cpp_info.name = "EXPAT"
```

**Comment by cqjjjzr** [comment]
Currently such code isn't in the expat recipe in CCI. Also, this requires us to properly set `cpp_info.name` of ALL dependencies of wxWidgets to support this.

Is there any way to provide `EXPATTargets.cmake` only for expat while other dependencies still use legacy approaches??

**Comment by SSE4** [comment]
@cqjjjzr I've opened PR for this: https://github.com/conan-io/conan-center-index/pull/198
I believe the long-term plan, is to use this approach for all packages, and switch them one by one
for now, I guess we can merge this PR as is, and reconsider once we move wxwidgets to CCI (as it doesn't allow to have this hard-coded cmake files).

**Comment by cqjjjzr** [comment]
Agree.

**Comment by cqjjjzr** [comment]
One more question.

The latest release of wxWidgets have some problems on the latest macOS Catalina platform. But building from wxWidgets source tree seems to have fixed those problems. Is there an approach to use latest nightly build in conan?

**Comment by Croydon** [comment]
> Is there an approach to use latest nightly build in conan?

We don't publish any nightly / pre-release versions. What we sometimes do is creating a patch from (future) upstream changes and applying it to the current release if possible and when there is a good reason for it.

**Comment by Croydon** [comment]
Is this still required? Did someone re-test with the CMake generators?

**Comment by cqjjjzr** [comment]
I've already checked this fix on Windows and macOS. It seems to work well. And since wxWidgets 3.1.3 was released, we no longer need the nightly build to get some new patches.

Currently the CI failures on macOS are due to some bugs which are fixed in 3.1.3, and Linux failures are due to new compilers.

**Comment by Croydon** [comment]
Closing in favour of  #19

**Pull request closed without merging**
